// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAccountModels(arg1) {
  return window['go']['main']['App']['GetAccountModels'](arg1);
}

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function GetBreakdown() {
  return window['go']['main']['App']['GetBreakdown']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCurrentAccount() {
  return window['go']['main']['App']['GetCurrentAccount']();
}

export function GetHealth() {
  return window['go']['main']['App']['GetHealth']();
}

export function GetLatestSnapshot(arg1) {
  return window['go']['main']['App']['GetLatestSnapshot'](arg1);
}

export function GetModelsLatest() {
  return window['go']['main']['App']['GetModelsLatest']();
}

export function GetSnapshots(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetSnapshots'](arg1, arg2, arg3);
}

export function GetSparklines(arg1) {
  return window['go']['main']['App']['GetSparklines'](arg1);
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetTimeline(arg1) {
  return window['go']['main']['App']['GetTimeline'](arg1);
}

export function GetTimeseries(arg1, arg2) {
  return window['go']['main']['App']['GetTimeseries'](arg1, arg2);
}

export function SetConfig(arg1) {
  return window['go']['main']['App']['SetConfig'](arg1);
}
