// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {apiclient} from '../models';
import {config} from '../models';

export function GetAccountModels(arg1:string):Promise<apiclient.AccountModelsResponse>;

export function GetAccounts():Promise<apiclient.AccountsResponse>;

export function GetBreakdown():Promise<apiclient.BreakdownResponse>;

export function GetConfig():Promise<config.Config>;

export function GetCurrentAccount():Promise<apiclient.CurrentAccount>;

export function GetHealth():Promise<apiclient.Health>;

export function GetLatestSnapshot(arg1:string):Promise<apiclient.Snapshot>;

export function GetModelsLatest():Promise<apiclient.ModelsLatestResponse>;

export function GetSnapshots(arg1:string,arg2:number,arg3:string):Promise<apiclient.SnapshotsResponse>;

export function GetSparklines(arg1:string):Promise<apiclient.SparklinesResponse>;

export function GetStats():Promise<apiclient.Stats>;

export function GetStatus():Promise<apiclient.DaemonStatus>;

export function GetTimeline(arg1:string):Promise<apiclient.TimelineResponse>;

export function GetTimeseries(arg1:string,arg2:string):Promise<apiclient.TimeseriesResponse>;

export function SetConfig(arg1:config.Config):Promise<config.Config>;
